### ISSUE TITLE
탈퇴한 회원/존재하지 않는 회원 로그인 시 Exception 제안 건

### ISSUE THREAD

**Issue by busymidnight** [duck-map-project/duck-map-be#237]
## Description
> 
<img width="906" alt="스크린샷 2023-06-09 오후 3 56 19" src="https://github.com/duck-map-project/duck-map-be/assets/100250055/8758c4ae-363a-493e-b0d6-8cea900b9df4">

현재 로그인 로직은 먼저 Spring Security 인증 단계를 진행하기 때문에 존재하지 않는 회원(혹은 탈퇴한 회원)이 로그인 하면 스크린샷과 같이 잘못된 인증이라는 오류를 보냅니다. 의미는 비슷하지만 InvalidMemberException이 먼저 나오는게 맞지 않나 하는 의문이 들어 제안합니다.

## To-do
- [ ] 로그인 시 인증 전에 회원이 있는지 먼저 확인하여 InvalidMemberException 처리
- [ ] 혹은 잘못된 인증이 맞으므로 현재 상태 유지

**Comment by busymidnight** [comment]
@LeeRim

**Comment by LeeRim** [comment]
단순 response message만 변경하고 싶으시면 AuthAdvice에서 수정하면 될거 같아요
InvalidMemberException을 발생시키고 싶으시면 AuthenticationEntryPoint에서 throw InvalidMemberException 하면 될거 같아요
회원이 있는지 확인하면 디비 조회가 발생해서요

**Comment by busymidnight** [comment]
> 단순 response message만 변경하고 싶으시면 AuthAdvice에서 수정하면 될거 같아요
> InvalidMemberException을 발생시키고 싶으시면 AuthenticationEntryPoint에서 throw InvalidMemberException 하면 될거 같아요
> 회원이 있는지 확인하면 디비 조회가 발생해서요

디비 조회는 불필요한것같아서 말씀하신대로 AuthenticationEntryPoint에서 throw InvalidMemberException하는게 나을것같아요! 
그럼 그렇게 수정할게요

**Comment by LeeRim** [comment]
> > 단순 response message만 변경하고 싶으시면 AuthAdvice에서 수정하면 될거 같아요
> > InvalidMemberException을 발생시키고 싶으시면 AuthenticationEntryPoint에서 throw InvalidMemberException 하면 될거 같아요
> > 회원이 있는지 확인하면 디비 조회가 발생해서요
> 
> 디비 조회는 불필요한것같아서 말씀하신대로 AuthenticationEntryPoint에서 throw InvalidMemberException하는게 나을것같아요! 
> 그럼 그렇게 수정할게요

네 알겠습니다

**Comment by busymidnight** [comment]
> > > 단순 response message만 변경하고 싶으시면 AuthAdvice에서 수정하면 될거 같아요
> > > InvalidMemberException을 발생시키고 싶으시면 AuthenticationEntryPoint에서 throw InvalidMemberException 하면 될거 같아요
> > > 회원이 있는지 확인하면 디비 조회가 발생해서요
> > 
> > 
> > 디비 조회는 불필요한것같아서 말씀하신대로 AuthenticationEntryPoint에서 throw InvalidMemberException하는게 나을것같아요!
> > 그럼 그렇게 수정할게요
> 
> 네 알겠습니다

<img width="1369" alt="스크린샷 2023-06-09 오후 5 00 43" src="https://github.com/duck-map-project/duck-map-be/assets/100250055/1f4f66ff-1c2a-44de-a2be-6297770f6c9c">

AuthenticationEntryPoint에서 지정해도... AuthenticationException이 먼저 일어나네요
AuthenticationException 메시지는 지금이 나은 것 같아서 변경하지 않을게요!
