### ISSUE TITLE
로그인시 마지막 검색 아티스트 반환 추가

### ISSUE THREAD

**Issue by LeeRim** [duck-map-project/duck-map-be#80]
## Description
> /login response에 LastSearchArtist값으로 artist pk 반환 추가

**Comment by busymidnight** [comment]
@LeeRim

**Comment by busymidnight** [comment]
> @busymidnight 적용 부탁드립니다! assigness에 쁜새님으로 변경했어요
LoginUserRes에만 long lastSearchArtist으로 추가하면 될까용?
아니면 controller에서 loginUserRQ로 받아오는 값인가욥?

**Comment by LeeRim** [comment]
> > @busymidnight 적용 부탁드립니다! assigness에 쁜새님으로 변경했어요
> > LoginUserRes에만 long lastSearchArtist으로 추가하면 될까용?
> > 아니면 controller에서 loginUserRQ로 받아오는 값인가욥?

LoginUserRes에만요!
마지막 검색 기록을 로그인 request에서 받을 수는 없을거 같아용

**Comment by busymidnight** [comment]
> > > @busymidnight 적용 부탁드립니다! assigness에 쁜새님으로 변경했어요
> > > LoginUserRes에만 long lastSearchArtist으로 추가하면 될까용?
> > > 아니면 controller에서 loginUserRQ로 받아오는 값인가욥?
> 
> LoginUserRes에만요! 마지막 검색 기록을 로그인 request에서 받을 수는 없을거 같아용

그러면 mock-api에서 현재는 그냥 임의값 넣어서 반환하도록 수정하면 될까용?

**Comment by LeeRim** [comment]
> > > > @busymidnight 적용 부탁드립니다! assigness에 쁜새님으로 변경했어요
> > > > LoginUserRes에만 long lastSearchArtist으로 추가하면 될까용?
> > > > 아니면 controller에서 loginUserRQ로 받아오는 값인가욥?
> > 
> > 
> > LoginUserRes에만요! 마지막 검색 기록을 로그인 request에서 받을 수는 없을거 같아용
> 
> 그러면 mock-api에서 현재는 그냥 임의값 넣어서 반환하도록 수정하면 될까용?

네!
